package org.example.rentathingproba.exceptions;

//Error codes for frontend
public enum ErrorCode {
    AUTH_ACCOUNT_NOT_VERIFIED,
    AUTH_INVALID_CREDENTIALS,
    AUTH_ACCOUNT_ALREADY_VERIFIED,
    AUTH_VERIFICATION_CODE_EXPIRED,
    AUTH_VERIFICATION_CODE_INVALID,
    AUTH_UNAUTHORIZED,

    //new bugs
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,

    USER_NOT_FOUND,

    THING_NOT_FOUND,
    THING_OWNERSHIP_REQUIRED,

    LISTING_NOT_FOUND,
    LISTING_OWNERSHIP_REQUIRED,

    VALIDATION_INVALID_INPUT,

    //Generic
    INTERNAL_ERROR
}
